// Mocks generated by Mockito 5.4.5 from annotations
// in flowery_delivery/test/features/auth/domain/use_cases/signup_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery_delivery/core/networking/common/api_result.dart' as _i4;
import 'package:flowery_delivery/features/auth/data/models/response/reset_password_response_dto.dart'
    as _i14;
import 'package:flowery_delivery/features/auth/data/models/response/verify_reset_code_response.dart'
    as _i12;
import 'package:flowery_delivery/features/auth/domain/contracts/auth_repo.dart'
    as _i2;
import 'package:flowery_delivery/features/auth/domain/entities/request/forget_password_request_entity.dart'
    as _i11;
import 'package:flowery_delivery/features/auth/domain/entities/request/login_request_entity.dart'
    as _i6;
import 'package:flowery_delivery/features/auth/domain/entities/request/reset_password_request_entity.dart'
    as _i15;
import 'package:flowery_delivery/features/auth/domain/entities/request/signup_request_entity.dart'
    as _i9;
import 'package:flowery_delivery/features/auth/domain/entities/request/verify_reset_code_request_entity.dart'
    as _i13;
import 'package:flowery_delivery/features/auth/domain/entities/response/forget_password_response_entity.dart'
    as _i10;
import 'package:flowery_delivery/features/auth/domain/entities/response/login_response_entity.dart'
    as _i5;
import 'package:flowery_delivery/features/auth/domain/entities/response/signup_response_entity.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.DataResult<_i5.LoginResponseEntity>> login(
          _i6.LoginRequestEntity? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue: _i3.Future<_i4.DataResult<_i5.LoginResponseEntity>>.value(
            _i7.dummyValue<_i4.DataResult<_i5.LoginResponseEntity>>(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.DataResult<_i5.LoginResponseEntity>>);

  @override
  _i3.Future<_i4.DataResult<_i8.SignUpResponseEntity>> signUp(
          {required _i9.SignUpRequestEntity? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {#request: request},
        ),
        returnValue: _i3.Future<_i4.DataResult<_i8.SignUpResponseEntity>>.value(
            _i7.dummyValue<_i4.DataResult<_i8.SignUpResponseEntity>>(
          this,
          Invocation.method(
            #signUp,
            [],
            {#request: request},
          ),
        )),
      ) as _i3.Future<_i4.DataResult<_i8.SignUpResponseEntity>>);

  @override
  _i3.Future<_i4.DataResult<_i10.ForgetPasswordResponseEntity>> forgetPassword(
          {required _i11.ForgetPasswordRequestEntity? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [],
          {#request: request},
        ),
        returnValue: _i3
            .Future<_i4.DataResult<_i10.ForgetPasswordResponseEntity>>.value(
            _i7.dummyValue<_i4.DataResult<_i10.ForgetPasswordResponseEntity>>(
          this,
          Invocation.method(
            #forgetPassword,
            [],
            {#request: request},
          ),
        )),
      ) as _i3.Future<_i4.DataResult<_i10.ForgetPasswordResponseEntity>>);

  @override
  _i3.Future<_i4.DataResult<_i12.VerifyResetCodeResponseDto>> verifyResetCode(
          {required _i13.VerifyResetCodeRequestEntity? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [],
          {#request: request},
        ),
        returnValue:
            _i3.Future<_i4.DataResult<_i12.VerifyResetCodeResponseDto>>.value(
                _i7.dummyValue<_i4.DataResult<_i12.VerifyResetCodeResponseDto>>(
          this,
          Invocation.method(
            #verifyResetCode,
            [],
            {#request: request},
          ),
        )),
      ) as _i3.Future<_i4.DataResult<_i12.VerifyResetCodeResponseDto>>);

  @override
  _i3.Future<_i4.DataResult<_i14.ResetPasswordResponseDto>> resetPassword(
          {required _i15.ResetPasswordRequestEntity? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {#request: request},
        ),
        returnValue:
            _i3.Future<_i4.DataResult<_i14.ResetPasswordResponseDto>>.value(
                _i7.dummyValue<_i4.DataResult<_i14.ResetPasswordResponseDto>>(
          this,
          Invocation.method(
            #resetPassword,
            [],
            {#request: request},
          ),
        )),
      ) as _i3.Future<_i4.DataResult<_i14.ResetPasswordResponseDto>>);
}
