// Mocks generated by Mockito 5.4.5 from annotations
// in flowery_delivery/test/features/auth/data/data_sources/impl/auth_online_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:io' as _i19;

import 'package:flowery_delivery/core/networking/api/api_manager.dart' as _i11;
import 'package:flowery_delivery/features/auth/data/models/request/forget_password_request_dto.dart'
    as _i15;
import 'package:flowery_delivery/features/auth/data/models/request/login_request_dto.dart'
    as _i13;
import 'package:flowery_delivery/features/auth/data/models/request/reset_password_request_dto.dart'
    as _i17;
import 'package:flowery_delivery/features/auth/data/models/request/signup_request_dto.dart'
    as _i14;
import 'package:flowery_delivery/features/auth/data/models/request/verify_reset_code_request_dto.dart'
    as _i16;
import 'package:flowery_delivery/features/auth/data/models/response/forget_password_response_dto.dart'
    as _i4;
import 'package:flowery_delivery/features/auth/data/models/response/login_response_dto.dart'
    as _i2;
import 'package:flowery_delivery/features/auth/data/models/response/reset_password_response_dto.dart'
    as _i6;
import 'package:flowery_delivery/features/auth/data/models/response/signup_response_dto.dart'
    as _i3;
import 'package:flowery_delivery/features/auth/data/models/response/verify_reset_code_response.dart'
    as _i5;
import 'package:flowery_delivery/features/profile/data/models/request/change_password_request_dto.dart'
    as _i18;
import 'package:flowery_delivery/features/profile/data/models/response/change_password_response_dto.dart'
    as _i9;
import 'package:flowery_delivery/features/profile/data/models/response/edit_profile_response_dto.dart'
    as _i8;
import 'package:flowery_delivery/features/profile/data/models/response/get_logged_user_data_response_dto.dart'
    as _i7;
import 'package:flowery_delivery/features/profile/data/models/response/upload_photo_response_dto.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponseDto_0 extends _i1.SmartFake
    implements _i2.LoginResponseDto {
  _FakeLoginResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignUpResponseDto_1 extends _i1.SmartFake
    implements _i3.SignUpResponseDto {
  _FakeSignUpResponseDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForgetPasswordResponseDto_2 extends _i1.SmartFake
    implements _i4.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyResetCodeResponseDto_3 extends _i1.SmartFake
    implements _i5.VerifyResetCodeResponseDto {
  _FakeVerifyResetCodeResponseDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResponseDto_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetLoggedUserDataResponseDto_5 extends _i1.SmartFake
    implements _i7.GetLoggedUserDataResponseDto {
  _FakeGetLoggedUserDataResponseDto_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEditProfileResponseDto_6 extends _i1.SmartFake
    implements _i8.EditProfileResponseDto {
  _FakeEditProfileResponseDto_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChangePasswordResponseDto_7 extends _i1.SmartFake
    implements _i9.ChangePasswordResponseDto {
  _FakeChangePasswordResponseDto_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUploadPhotoResponseDto_8 extends _i1.SmartFake
    implements _i10.UploadPhotoResponseDto {
  _FakeUploadPhotoResponseDto_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManager extends _i1.Mock implements _i11.ApiManager {
  MockApiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i2.LoginResponseDto> login(_i13.LoginRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue:
            _i12.Future<_i2.LoginResponseDto>.value(_FakeLoginResponseDto_0(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i12.Future<_i2.LoginResponseDto>);

  @override
  _i12.Future<_i3.SignUpResponseDto> signUp(_i14.SignUpRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [request],
        ),
        returnValue:
            _i12.Future<_i3.SignUpResponseDto>.value(_FakeSignUpResponseDto_1(
          this,
          Invocation.method(
            #signUp,
            [request],
          ),
        )),
      ) as _i12.Future<_i3.SignUpResponseDto>);

  @override
  _i12.Future<_i4.ForgetPasswordResponseDto> forgetPassword(
          _i15.ForgetPasswordRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [request],
        ),
        returnValue: _i12.Future<_i4.ForgetPasswordResponseDto>.value(
            _FakeForgetPasswordResponseDto_2(
          this,
          Invocation.method(
            #forgetPassword,
            [request],
          ),
        )),
      ) as _i12.Future<_i4.ForgetPasswordResponseDto>);

  @override
  _i12.Future<_i5.VerifyResetCodeResponseDto> verifyResetCode(
          _i16.VerifyResetCodeRequestDto? resetCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [resetCode],
        ),
        returnValue: _i12.Future<_i5.VerifyResetCodeResponseDto>.value(
            _FakeVerifyResetCodeResponseDto_3(
          this,
          Invocation.method(
            #verifyResetCode,
            [resetCode],
          ),
        )),
      ) as _i12.Future<_i5.VerifyResetCodeResponseDto>);

  @override
  _i12.Future<_i6.ResetPasswordResponseDto> resetPassword(
          _i17.ResetPasswordRequestDto? resetPassword) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [resetPassword],
        ),
        returnValue: _i12.Future<_i6.ResetPasswordResponseDto>.value(
            _FakeResetPasswordResponseDto_4(
          this,
          Invocation.method(
            #resetPassword,
            [resetPassword],
          ),
        )),
      ) as _i12.Future<_i6.ResetPasswordResponseDto>);

  @override
  _i12.Future<_i7.GetLoggedUserDataResponseDto> getLoggedUserData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLoggedUserData,
          [],
        ),
        returnValue: _i12.Future<_i7.GetLoggedUserDataResponseDto>.value(
            _FakeGetLoggedUserDataResponseDto_5(
          this,
          Invocation.method(
            #getLoggedUserData,
            [],
          ),
        )),
      ) as _i12.Future<_i7.GetLoggedUserDataResponseDto>);

  @override
  _i12.Future<_i8.EditProfileResponseDto> editProfile(
          Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [body],
        ),
        returnValue: _i12.Future<_i8.EditProfileResponseDto>.value(
            _FakeEditProfileResponseDto_6(
          this,
          Invocation.method(
            #editProfile,
            [body],
          ),
        )),
      ) as _i12.Future<_i8.EditProfileResponseDto>);

  @override
  _i12.Future<_i9.ChangePasswordResponseDto> changePassword(
          _i18.ChangePasswordRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [request],
        ),
        returnValue: _i12.Future<_i9.ChangePasswordResponseDto>.value(
            _FakeChangePasswordResponseDto_7(
          this,
          Invocation.method(
            #changePassword,
            [request],
          ),
        )),
      ) as _i12.Future<_i9.ChangePasswordResponseDto>);

  @override
  _i12.Future<_i10.UploadPhotoResponseDto> uploadPhoto(_i19.File? photo) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [photo],
        ),
        returnValue: _i12.Future<_i10.UploadPhotoResponseDto>.value(
            _FakeUploadPhotoResponseDto_8(
          this,
          Invocation.method(
            #uploadPhoto,
            [photo],
          ),
        )),
      ) as _i12.Future<_i10.UploadPhotoResponseDto>);
}
