name: flowery_delivery
description: "flowery_delivery"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Cupertino icons
  cupertino_icons: ^1.0.6

  # Core functionality
  bloc_test: ^9.1.7
  badges: ^3.1.1
  row_item: ^2.2.1+1
  dio: ^5.7.0
  retrofit: ^4.4.1
  logger: ^2.5.0
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.4
  build_runner: ^2.4.14
  awesome_snackbar_content: ^0.1.4
  connectivity_plus: ^6.1.1
  cached_network_image: ^3.4.1
  flutter_localization: ^0.3.0
  intl_utils: ^2.8.7
  country_state_city: ^0.1.6
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1

  # UI
  lottie: ^3.3.0
  flutter_hooks: ^0.20.5
  equatable: ^2.0.7
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  flutter_image_slideshow: ^0.1.6
  add_to_cart_animation: ^2.0.4
  auto_size_text: ^3.0.0
  image_picker: ^1.1.2
  animate_do: ^3.3.4

  # Dependency Injection
  injectable: ^2.5.0
  get_it: ^8.0.3

  # State management
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16
  bloc: ^8.1.4
  geolocator: ^13.0.2
  geocoding: ^3.0.0

  # Firebase
  firebase_core: ^3.9.0
  firebase_crashlytics: ^4.2.0
  firebase_analytics: ^11.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_intl: ^0.0.1
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.0
  json_serializable: ^6.8.0
  dartz: ^0.10.1
  test: ^1.25.8
  mockito: ^5.4.5
  flutter_native_splash: ^2.4.3
  icons_launcher: ^3.0.0
  rename: ^3.0.2



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - lib/generated/assets.dart
    - .env.firebase
    - translations/ar.json
    - translations/en.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: oronteus
      fonts:
        - asset: assets/fonts/oronteus_finaeus.ttf
