// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get('WEB_WINDOWS_API_KEY'),
    appId: dotenv.get('WEB_APP_ID'),
    messagingSenderId: dotenv.get('MESSAGING_SENDER_ID'),
    projectId: dotenv.get('PROJECT_ID'),
    authDomain: dotenv.get('AUTH_DOMAIN'),
    storageBucket: dotenv.get('STORAGE_BUCKET'),
    measurementId: dotenv.get('MEASUREMENT_ID'),
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get('ANDROID_API_KEY'),
    appId: dotenv.get('ANDROID_APP_ID'),
    messagingSenderId: dotenv.get('MESSAGING_SENDER_ID'),
    projectId: dotenv.get('PROJECT_ID'),
    storageBucket: dotenv.get('STORAGE_BUCKET'),
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get('IOS_MACOS_API_KEY'),
    appId: dotenv.get('IOS_MACOS_APP_ID'),
    messagingSenderId: dotenv.get('MESSAGING_SENDER_ID'),
    projectId: dotenv.get('PROJECT_ID'),
    storageBucket: dotenv.get('STORAGE_BUCKET'),
    iosBundleId: dotenv.get('IOS_MACOS_BUNDLE_ID'),
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.get('IOS_MACOS_API_KEY'),
    appId: dotenv.get('IOS_MACOS_APP_ID'),
    messagingSenderId: dotenv.get('MESSAGING_SENDER_ID'),
    projectId: dotenv.get('PROJECT_ID'),
    storageBucket: dotenv.get('STORAGE_BUCKET'),
    iosBundleId: dotenv.get('IOS_MACOS_BUNDLE_ID'),
  );

  static  FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.get('WEB_WINDOWS_API_KEY'),
    appId: dotenv.get('WINDOWS_APP_ID'),
    messagingSenderId: dotenv.get('MESSAGING_SENDER_ID'),
    projectId: dotenv.get('PROJECT_ID'),
    authDomain: dotenv.get('AUTH_DOMAIN'),
    storageBucket: dotenv.get('STORAGE_BUCKET'),
    measurementId: dotenv.get('WINDOWS_MEASUREMENT_ID'),
  );
}
